// <auto-generated />
using System;
using FoodPriceComparison.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodPriceComparison.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250923165032_SeedPlatformPrices")]
    partial class SeedPlatformPrices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodPriceComparison.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("FoodPriceComparison.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"));

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("FoodPriceComparison.Models.PlatformPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PlatformPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishName = "Margherita Pizza",
                            PlatformName = "Zomato",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            DishName = "Margherita Pizza",
                            PlatformName = "Swiggy",
                            Price = 270m
                        },
                        new
                        {
                            Id = 3,
                            DishName = "Margherita Pizza",
                            PlatformName = "UberEats",
                            Price = 260m
                        },
                        new
                        {
                            Id = 4,
                            DishName = "Veg Burger",
                            PlatformName = "Zomato",
                            Price = 120m
                        },
                        new
                        {
                            Id = 5,
                            DishName = "Veg Burger",
                            PlatformName = "Swiggy",
                            Price = 110m
                        },
                        new
                        {
                            Id = 6,
                            DishName = "Veg Burger",
                            PlatformName = "UberEats",
                            Price = 115m
                        },
                        new
                        {
                            Id = 7,
                            DishName = "Pasta Alfredo",
                            PlatformName = "Zomato",
                            Price = 180m
                        },
                        new
                        {
                            Id = 8,
                            DishName = "Pasta Alfredo",
                            PlatformName = "Swiggy",
                            Price = 175m
                        },
                        new
                        {
                            Id = 9,
                            DishName = "Pasta Alfredo",
                            PlatformName = "UberEats",
                            Price = 185m
                        },
                        new
                        {
                            Id = 10,
                            DishName = "French Fries",
                            PlatformName = "Zomato",
                            Price = 90m
                        },
                        new
                        {
                            Id = 11,
                            DishName = "French Fries",
                            PlatformName = "Swiggy",
                            Price = 85m
                        },
                        new
                        {
                            Id = 12,
                            DishName = "French Fries",
                            PlatformName = "UberEats",
                            Price = 95m
                        });
                });

            modelBuilder.Entity("FoodPriceComparison.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("FoodPriceComparison.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
